### PR TITLE
Git copy content

### PR DESCRIPTION
**Pull request by liamhuber**
From `pyiron_workflow`, which in turn git-copied from `pyiron_base` and perhaps other places

### CODE REVIEW

**Comment by liamhuber** [comment]
I thought I might run into this; the conda merge fails because the env file has no dependencies:

```
Run python $GITHUB_ACTION_PATH/../.support/condamerge.py $GITHUB_ACTION_PATH/../.support/environment-unittests.yml $GITHUB_ACTION_PATH/../.support/environment-coveralls-codacy.yml .ci_support/environment.yml .ci_support/environment-tests.yml > ./environment.yml
Traceback (most recent call last):
  File "/home/runner/work/_actions/pyiron/actions/v3.1.0/write-environment/../.support/condamerge.py", line 80, in <module>
    merge_env(
  File "/home/runner/work/_actions/pyiron/actions/v3.1.0/write-environment/../.support/condamerge.py", line 68, in merge_env
    'dependencies': merge_dependencies(
  File "/home/runner/work/_actions/pyiron/actions/v3.1.0/write-environment/../.support/condamerge.py", line 43, in merge_dependencies
    add_dict, add_pip_dict = split_dependencies(env_add)
  File "/home/runner/work/_actions/pyiron/actions/v3.1.0/write-environment/../.support/condamerge.py", line 25, in split_dependencies
    for f in env:
TypeError: 'NoneType' object is not iterable
```

I'm going to just add "python" and see if that minimal change will do it.

**Comment by liamhuber** [comment]
@samwaseda since `files` is a non-trivial chunk by line count, I'm sticking you with review and put you in the author list.

This just (git)copies everything from `pyiron_workflow.snippets` over to this repo, minus the pyiron test case, which (a) I don't think we really need now that we have other (IMO nicer) ways of testing the docs (cf. the integration test here), and (b) it wants to import numpy and is thus at least a little against the spirit of the business here.

If you're happy with this, I'd prefer to squash merge so the initial content commit is all one piece.

**Comment by samwaseda** [comment]
Yeah I was thinking about moving them as well. I’m super happy with the decision

**Review by samwaseda — APPROVED** [review]

**Comment by samwaseda** [comment]
Ah I thought it was `pyiron_base`. I'm also ok with a new repo, but do we have a clear dependency hierarchy somewhere for all the pyiron modules? I'm a bit concerned that we/I might lose an overview.

**Comment by liamhuber** [comment]
This has zero of its own dependencies, so can be mixed in wherever. E.g. one of the first things I want to do with it once it's on conda (besides replacing the code in pyiron workflow) is to search and replace all uses of the Singleton class, which I know is at least in base.

**Pull request merged**
